# Generated by Django 3.2.18 on 2023-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_alter_invoice_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitems',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimateitems',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimateitems',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
