# Generated by Django 3.2.18 on 2023-05-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0005_pricelist_sample_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_table',
            name='baddress',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='battention',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='bcity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='bcountry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='bfax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='bphone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='bstate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='bzip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='saddress',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='sattention',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='scity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='scountry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='sfax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='sphone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='sstate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_table',
            name='szip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='remarks_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table')),
            ],
        ),
        migrations.CreateModel(
            name='contact_person_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('work_phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('skype_number', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table')),
            ],
        ),
    ]
