# Generated by Django 4.1.7 on 2023-05-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0011_alter_sample_table_price_banking_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accountType", models.CharField(max_length=255)),
                ("accountName", models.CharField(max_length=255)),
                ("accountCode", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=255)),
                ("repeat_every", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("ends_on", models.DateField()),
                ("expense_account", models.CharField(max_length=255)),
                ("expense_type", models.CharField(max_length=50)),
                ("goods_label", models.CharField(default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("paidthrough", models.CharField(max_length=50)),
                ("gst", models.CharField(blank=True, max_length=255)),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("tax", models.CharField(blank=True, max_length=255)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("customername", models.CharField(blank=True, max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zohoapp.vendor_table",
                    ),
                ),
            ],
        ),
    ]
