# Generated by Django 4.1.4 on 2023-06-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_payment_terms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_terms',
            name='user',
        ),
    ]
