# Generated by Django 4.1.4 on 2023-06-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_remove_payment_terms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_upload_table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doc_upload_table',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='mail_table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mail_table',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='baddress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='battention',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='bcity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='bcountry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='bfax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='bphone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='bstate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='bzip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='saddress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='sattention',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='scity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='scountry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='sfax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='sphone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='sstate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_table',
            name='szip',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='comments_table',
        ),
        migrations.DeleteModel(
            name='doc_upload_table',
        ),
        migrations.DeleteModel(
            name='mail_table',
        ),
    ]
