# Generated by Django 4.1.4 on 2023-06-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_mail_table_doc_upload_table_comments_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
